import type { Blog } from "@/types";

export const mockBlogs: Blog[] = [
  {
    id: "blog-001",
    title: "Top 10 Engineering Colleges to Explore at Career Utsav 2026",
    slug: "top-10-engineering-colleges-career-utsav-2026",
    excerpt:
      "Planning to attend Career Utsav? Here are the must-visit engineering college stalls across Bengaluru and Delhi editions.",
    content:
      "Career Utsav brings together India's finest engineering institutions under one roof. From IIT Bombay to DTU Delhi, students can interact directly with admission counsellors, faculty members, and alumni. This guide highlights the top 10 stalls you shouldn't miss, including scholarship opportunities and campus tour details.",
    coverImage: "/images/blogs/top-engineering-colleges.jpg",
    author: "Vikram Singh",
    authorId: "usr-004",
    status: "Published",
    tags: ["Engineering", "College Selection", "Career Tips"],
    viewCount: 4520,
    readTimeMinutes: 8,
    publishedAt: "2026-06-01T10:00:00+05:30",
    createdAt: "2026-05-28T14:00:00+05:30",
    updatedAt: "2026-06-01T10:00:00+05:30",
  },
  {
    id: "blog-002",
    title: "How to Prepare for Your First Career Fair: A Student's Guide",
    slug: "how-to-prepare-first-career-fair-student-guide",
    excerpt:
      "First time at a career fair? Learn how to make the most of your visit with these practical tips from Career Utsav organisers.",
    content:
      "Walking into a career fair with 150+ university stalls can feel overwhelming. Start by researching participating institutions online, prepare a list of questions, carry multiple copies of your resume, and dress professionally. Our team recommends arriving early to avoid crowds and attending at least two workshop sessions.",
    coverImage: "/images/blogs/first-career-fair-guide.jpg",
    author: "Sneha Iyer",
    authorId: "usr-009",
    status: "Published",
    tags: ["Career Tips", "Students", "Events"],
    viewCount: 3890,
    readTimeMinutes: 6,
    publishedAt: "2026-05-15T09:00:00+05:30",
    createdAt: "2026-05-10T11:00:00+05:30",
    updatedAt: "2026-05-15T09:00:00+05:30",
  },
  {
    id: "blog-003",
    title: "Study Abroad Opportunities at Career Utsav Delhi NCR 2026",
    slug: "study-abroad-opportunities-delhi-ncr-2026",
    excerpt:
      "IDP Education and Leverage Edu join Career Utsav Delhi NCR with dedicated study abroad counselling zones.",
    content:
      "The Delhi NCR edition features a dedicated Study Abroad Pavilion with representatives from UK, USA, Canada, and Australia. Free IELTS preparation workshops, scholarship guidance sessions, and one-on-one counselling slots are available throughout the two-day event at Pragati Maidan.",
    coverImage: "/images/blogs/study-abroad-delhi.jpg",
    author: "Ananya Reddy",
    authorId: "usr-003",
    status: "Published",
    tags: ["Study Abroad", "Delhi NCR", "Scholarships"],
    viewCount: 2340,
    readTimeMinutes: 5,
    publishedAt: "2026-06-20T10:00:00+05:30",
    createdAt: "2026-06-18T15:00:00+05:30",
    updatedAt: "2026-06-20T10:00:00+05:30",
  },
  {
    id: "blog-004",
    title: "Career Utsav Mumbai 2025: Event Highlights and Key Takeaways",
    slug: "career-utsav-mumbai-2025-highlights",
    excerpt:
      "Over 11,000 students attended Career Utsav Mumbai 2025. Here's a recap of the most impactful sessions and outcomes.",
    content:
      "Career Utsav Mumbai 2025 at NESCO Grounds was our largest Maharashtra edition yet. Accenture hosted a live hackathon, Symbiosis conducted MBA admission previews, and HDFC Bank's education loan kiosk processed over 500 enquiries. Student feedback rated the finance and design workshops as the event highlights.",
    coverImage: "/images/blogs/mumbai-2025-highlights.jpg",
    author: "Vikram Singh",
    authorId: "usr-004",
    status: "Published",
    tags: ["Event Recap", "Mumbai", "Highlights"],
    viewCount: 5670,
    readTimeMinutes: 10,
    publishedAt: "2025-12-15T11:00:00+05:30",
    createdAt: "2025-12-12T09:00:00+05:30",
    updatedAt: "2025-12-15T11:00:00+05:30",
  },
  {
    id: "blog-005",
    title: "NEET vs JEE: Choosing Your Path After Class 12",
    slug: "neet-vs-jee-choosing-path-after-class-12",
    excerpt:
      "Confused between medical and engineering? Expert counsellors at Career Utsav Hyderabad share insights on making the right choice.",
    content:
      "The decision between NEET and JEE is one of the most critical choices for Class 12 science students. At Career Utsav Hyderabad, dedicated sessions cover exam patterns, career prospects, salary benchmarks, and alternative pathways including integrated programs and study abroad options for both streams.",
    coverImage: "/images/blogs/neet-vs-jee.jpg",
    author: "Sneha Iyer",
    authorId: "usr-009",
    status: "Published",
    tags: ["NEET", "JEE", "Career Counselling"],
    viewCount: 8120,
    readTimeMinutes: 12,
    publishedAt: "2026-06-25T09:00:00+05:30",
    createdAt: "2026-06-22T14:00:00+05:30",
    updatedAt: "2026-06-25T09:00:00+05:30",
  },
  {
    id: "blog-006",
    title: "Why Universities Should Partner with Career Utsav",
    slug: "why-universities-should-partner-career-utsav",
    excerpt:
      "Reach 50,000+ qualified students annually. Learn about stall packages, branding benefits, and lead generation for universities.",
    content:
      "Career Utsav offers universities a unique platform to connect with pre-qualified students actively seeking higher education. Our 2025 data shows an average of 340 serious enquiries per university stall, with 28% converting to application submissions within 30 days of the event.",
    coverImage: "/images/blogs/university-partnership.jpg",
    author: "Priya Sharma",
    authorId: "usr-002",
    status: "Published",
    tags: ["Universities", "Partnership", "B2B"],
    viewCount: 1890,
    readTimeMinutes: 7,
    publishedAt: "2026-04-10T10:00:00+05:30",
    createdAt: "2026-04-05T11:00:00+05:30",
    updatedAt: "2026-04-10T10:00:00+05:30",
  },
  {
    id: "blog-007",
    title: "Career Utsav Chennai 2026: What to Expect",
    slug: "career-utsav-chennai-2026-preview",
    excerpt:
      "Preview of the upcoming Tamil Nadu edition featuring Anna University affiliates and study abroad consultants.",
    content:
      "Career Utsav is expanding to Chennai in November 2026. The event will feature Anna University affiliated colleges, deemed universities from Tamil Nadu, and dedicated sessions for Tamil-medium students transitioning to English-medium professional courses. Registration opens August 2026.",
    author: "Vikram Singh",
    authorId: "usr-004",
    status: "Draft",
    tags: ["Chennai", "Preview", "Tamil Nadu"],
    viewCount: 0,
    readTimeMinutes: 5,
    createdAt: "2026-06-28T10:00:00+05:30",
    updatedAt: "2026-07-01T14:00:00+05:30",
  },
  {
    id: "blog-008",
    title: "Education Loan Guide for Indian Students in 2026",
    slug: "education-loan-guide-indian-students-2026",
    excerpt:
      "HDFC Bank and Career Utsav break down education loan options, interest rates, and documentation requirements.",
    content:
      "Financing higher education is a major concern for Indian families. This comprehensive guide covers government schemes, bank loan products, collateral requirements, and tax benefits under Section 80E. Special focus on loans for study abroad programs and professional courses.",
    coverImage: "/images/blogs/education-loan-guide.jpg",
    author: "Ananya Reddy",
    authorId: "usr-003",
    status: "Archived",
    tags: ["Finance", "Education Loans", "Students"],
    viewCount: 3210,
    readTimeMinutes: 9,
    publishedAt: "2025-08-01T10:00:00+05:30",
    createdAt: "2025-07-25T09:00:00+05:30",
    updatedAt: "2026-01-15T11:00:00+05:30",
  },
];
