import type {
  ChartDataPoint,
  CityComparisonMetric,
  CityDashboardSlice,
  DashboardInsight,
  DashboardKPI,
  DashboardTarget,
  OperatingCity,
  PartnerSalesAnalytics,
  RecentActivity,
  DashboardTask,
  UpcomingEventSummary,
  StudentRegistrationAnalytics,
} from "@/types";
import { CAREER_UTSAV_SEMINARS, SEMINAR_POPULARITY } from "@/features/dashboard/seminars";

export type { OperatingCity, CityComparisonMetric, CityDashboardSlice };

export const OPERATING_CITIES: OperatingCity[] = ["Bangalore", "Mysore", "Hubli"];

function buildSeminarInterest(total: number): ChartDataPoint[] {
  const weightSum = Object.values(SEMINAR_POPULARITY).reduce((s, w) => s + w, 0) || 1;
  return CAREER_UTSAV_SEMINARS.map((name) => ({
    name,
    value: Math.max(
      1,
      Math.round(((SEMINAR_POPULARITY[name] ?? 20) / weightSum) * total * 0.85)
    ),
  })).sort((a, b) => b.value - a.value);
}

/** Week-start labels Mon Aug 3 → Mon Dec 28, 2026 */
const WEEKLY_TREND_LABELS_2026 = [
  "3 Aug",
  "10 Aug",
  "17 Aug",
  "24 Aug",
  "31 Aug",
  "7 Sep",
  "14 Sep",
  "21 Sep",
  "28 Sep",
  "5 Oct",
  "12 Oct",
  "19 Oct",
  "26 Oct",
  "2 Nov",
  "9 Nov",
  "16 Nov",
  "23 Nov",
  "30 Nov",
  "7 Dec",
  "14 Dec",
  "21 Dec",
  "28 Dec",
] as const;

/**
 * Ramp Aug → peak late Oct / early Nov → soft Dec taper.
 * Values scale so the series sums roughly to `total`.
 */
function buildWeeklyTrend2026(total: number, accent = 1): ChartDataPoint[] {
  const shape = [
    0.35, 0.42, 0.48, 0.55, 0.62, 0.7, 0.78, 0.88, 0.95, 1.05, 1.15, 1.22, 1.28,
    1.32, 1.3, 1.22, 1.12, 1.02, 0.92, 0.82, 0.72, 0.62,
  ];
  const weightSum = shape.reduce((s, w) => s + w * accent, 0) || 1;
  return WEEKLY_TREND_LABELS_2026.map((name, i) => ({
    name,
    value: Math.max(
      1,
      Math.round(((shape[i] ?? 1) * accent * total) / weightSum)
    ),
  }));
}

/** All-cities totals used for reconciliation (see mockDashboardData). */
const ALL_CITIES_REGISTRATIONS = 43620;
const ALL_CITIES_REVENUE = 9845000;
const ALL_CITIES_CHECKINS = 6780;
const ALL_CITIES_PIPELINE = 24850000;
const ALL_CITIES_CONVERSION = 72.5;
const CITY_COUNT = OPERATING_CITIES.length;

const AVG_REGISTRATIONS = Math.round(ALL_CITIES_REGISTRATIONS / CITY_COUNT);
const AVG_REVENUE = Math.round(ALL_CITIES_REVENUE / CITY_COUNT);
const AVG_CHECKINS = Math.round(ALL_CITIES_CHECKINS / CITY_COUNT);
const AVG_PIPELINE = Math.round(ALL_CITIES_PIPELINE / CITY_COUNT);
const AVG_CONVERSION = ALL_CITIES_CONVERSION;

function deltaVsAverage(cityValue: number, averageValue: number): number {
  if (averageValue === 0) return 0;
  return Math.round(((cityValue - averageValue) / averageValue) * 1000) / 10;
}

function buildVsAverage(metrics: {
  registrations: number;
  revenue: number;
  conversion: number;
  pipeline: number;
  checkIns: number;
}): CityComparisonMetric[] {
  return [
    {
      id: "vs-registrations",
      label: "Students joining",
      cityValue: metrics.registrations,
      averageValue: AVG_REGISTRATIONS,
      format: "number",
      deltaPercent: deltaVsAverage(metrics.registrations, AVG_REGISTRATIONS),
    },
    {
      id: "vs-checkins",
      label: "Activity today",
      cityValue: metrics.checkIns,
      averageValue: AVG_CHECKINS,
      format: "number",
      deltaPercent: deltaVsAverage(metrics.checkIns, AVG_CHECKINS),
    },
    {
      id: "vs-partners",
      label: "Partner conversations",
      cityValue: metrics.pipeline,
      averageValue: AVG_PIPELINE,
      format: "number",
      deltaPercent: deltaVsAverage(metrics.pipeline, AVG_PIPELINE),
    },
  ];
}

// ─── Bangalore (~52.3% volume) ──────────────────────────────────────────────

const bangaloreStudentRegistration: StudentRegistrationAnalytics = {
  total: 22800,
  target: 28000,
  todayCount: 218,
  weeklyGrowth: 16.8,
  dailyTrend: [
    { name: "Jun 26", value: 98 },
    { name: "Jun 27", value: 112 },
    { name: "Jun 28", value: 104 },
    { name: "Jun 29", value: 126 },
    { name: "Jun 30", value: 141 },
    { name: "Jul 1", value: 155 },
    { name: "Jul 2", value: 164 },
    { name: "Jul 3", value: 146 },
    { name: "Jul 4", value: 188 },
    { name: "Jul 5", value: 256 },
    { name: "Jul 6", value: 272 },
    { name: "Jul 7", value: 208 },
    { name: "Jul 8", value: 192 },
    { name: "Jul 9", value: 228 },
    { name: "Jul 10", value: 218 },
  ],
  byClass: [
    { name: "Class 4", value: 220, segment: "lower" },
    { name: "Class 5", value: 355, segment: "lower" },
    { name: "Class 6", value: 585, segment: "lower" },
    { name: "Class 7", value: 825, segment: "lower" },
    { name: "Class 8", value: 1220, segment: "lower" },
    { name: "Class 9", value: 3200, segment: "core" },
    { name: "Class 10", value: 4680, segment: "core" },
    { name: "Class 11", value: 5380, segment: "core" },
    { name: "Class 12", value: 6335, segment: "core" },
  ],
  byStream: [
    { name: "Science", value: 11240 },
    { name: "Commerce", value: 6720 },
    { name: "Arts", value: 4840 },
  ],
  byBoard: [
    { name: "CBSE", value: 9720 },
    { name: "State Board", value: 4860 },
    { name: "ICSE", value: 3920 },
    { name: "PUC", value: 2680 },
    { name: "IB / IGCSE", value: 1620 },
  ],
  byGender: [
    { name: "Female", value: 11190 },
    { name: "Male", value: 11610 },
  ],
  byCity: [{ name: "Bangalore", value: 22800 }],
  byRegistrantCity: [
    { name: "Bangalore", value: 14280 },
    { name: "Whitefield", value: 1860 },
    { name: "Electronic City", value: 1420 },
    { name: "Yelahanka", value: 1180 },
    { name: "Tumkur", value: 980 },
    { name: "Kolar", value: 720 },
    { name: "Chikkaballapur", value: 640 },
    { name: "Ramanagara", value: 520 },
    { name: "Other / Out of state", value: 1200 },
  ],
  bySeminar: buildSeminarInterest(22800),
  weeklyTrend: buildWeeklyTrend2026(22800, 1.08),
  bySession: [
    { name: "Morning", value: 9640 },
    { name: "Afternoon", value: 7980 },
    { name: "Evening", value: 5180 },
  ],
  bySource: [
    { name: "School Outreach", value: 8820 },
    { name: "Website", value: 5860 },
    { name: "Social Media", value: 3580 },
    { name: "Referral", value: 2680 },
    { name: "Partner", value: 1860 },
  ],
  topSchools: [
    { name: "National Public School, Indiranagar", value: 654, city: "Bangalore" },
    { name: "Bishop Cotton Boys' School", value: 582, city: "Bangalore" },
    { name: "Delhi Public School, East", value: 518, city: "Bangalore" },
    { name: "Inventure Academy", value: 476, city: "Bangalore" },
    { name: "The International School Bangalore", value: 442, city: "Bangalore" },
    { name: "Ryan International, HSR", value: 398, city: "Bangalore" },
  ],
  topColleges: [
    { name: "Christ University", value: 318, city: "Bangalore" },
    { name: "St. Joseph's College", value: 274, city: "Bangalore" },
    { name: "Mount Carmel College", value: 248, city: "Bangalore" },
    { name: "PES University", value: 226, city: "Bangalore" },
    { name: "Jain University", value: 198, city: "Bangalore" },
    { name: "RV College of Engineering", value: 172, city: "Bangalore" },
  ],
  liveFeed: [
    {
      id: "blr-live-001",
      studentName: "Diya Krishnan",
      classLabel: "Class 11",
      stream: "Commerce",
      board: "PUC",
      school: "Mount Carmel PU College",
      city: "Bangalore",
      timestamp: "2026-07-10T21:42:00+05:30",
    },
    {
      id: "blr-live-002",
      studentName: "Vivaan Joshi",
      classLabel: "Class 8",
      board: "CBSE",
      school: "Ryan International, HSR",
      city: "Bangalore",
      timestamp: "2026-07-10T21:36:00+05:30",
    },
    {
      id: "blr-live-003",
      studentName: "Ananya Rao",
      classLabel: "Class 12",
      stream: "Science",
      board: "CBSE",
      school: "National Public School, Indiranagar",
      city: "Bangalore",
      timestamp: "2026-07-10T21:29:00+05:30",
    },
    {
      id: "blr-live-004",
      studentName: "Arjun Hegde",
      classLabel: "Class 10",
      stream: "Science",
      board: "ICSE",
      school: "Bishop Cotton Boys' School",
      city: "Bangalore",
      timestamp: "2026-07-10T21:21:00+05:30",
    },
    {
      id: "blr-live-005",
      studentName: "Meera Shetty",
      classLabel: "Class 9",
      stream: "Arts",
      board: "State Board",
      school: "Delhi Public School, East",
      city: "Bangalore",
      timestamp: "2026-07-10T21:14:00+05:30",
    },
    {
      id: "blr-live-006",
      studentName: "Kabir Menon",
      classLabel: "Class 12",
      stream: "Science",
      board: "IB / IGCSE",
      school: "The International School Bangalore",
      city: "Bangalore",
      timestamp: "2026-07-10T21:08:00+05:30",
    },
  ],
};

const bangalorePartnerSales: PartnerSalesAnalytics = {
  totalPartners: 44,
  confirmed: 18,
  inProcess: 21,
  lost: 5,
  pipelineValue: 13000000,
  wonValue: 4850000,
  conversionRate: 40.9,
  byTier: [
    { name: "Stall Partner", value: 9, amount: 900000 },
    { name: "Education Partner", value: 7, amount: 1400000 },
    { name: "Knowledge Partner (Silver)", value: 6, amount: 1800000 },
    { name: "Knowledge Partner (Gold)", value: 5, amount: 2500000 },
    { name: "University Partner", value: 8, amount: 2400000 },
    { name: "Co-Presenting Partner", value: 5, amount: 2500000 },
    { name: "Presenting Partner", value: 4, amount: 4000000 },
  ],
  byStage: [
    { name: "New", count: 7, amount: 1680000 },
    { name: "Contacted", count: 6, amount: 1440000 },
    { name: "Meeting Scheduled", count: 5, amount: 1620000 },
    { name: "Negotiation", count: 9, amount: 4080000 },
    { name: "Won", count: 12, amount: 4850000 },
    { name: "Lost", count: 5, amount: 1480000 },
  ],
  byStatus: [
    { name: "Confirmed", value: 18 },
    { name: "In Process", value: 21 },
    { name: "Lost", value: 5 },
  ],
  byCity: [
    { name: "Bangalore", value: 18 },
  ],
  tierProgress: [
    { name: "Stall Partner", current: 9, target: 12, value: 900000 },
    { name: "Education Partner", current: 7, target: 10, value: 1400000 },
    { name: "Knowledge Partner (Silver)", current: 6, target: 8, value: 1800000 },
    { name: "Knowledge Partner (Gold)", current: 5, target: 6, value: 2500000 },
    { name: "University Partner", current: 8, target: 9, value: 2400000 },
    { name: "Co-Presenting Partner", current: 5, target: 6, value: 2500000 },
    { name: "Presenting Partner", current: 4, target: 4, value: 4000000 },
  ],
  recentActivity: [
    {
      id: "blr-psa-001",
      title: "Negotiation",
      description: "Christ University received Knowledge Partner (Gold) proposal",
      timestamp: "2026-07-10T16:15:00+05:30",
      universityName: "Christ University",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      value: 550000,
    },
    {
      id: "blr-psa-002",
      title: "Deal won — Stall Partner",
      description: "Jain University confirmed Stall Partner for Bangalore",
      timestamp: "2026-07-06T09:30:00+05:30",
      universityName: "Jain University",
      tier: "Stall Partner",
      stage: "Won",
      value: 100000,
    },
    {
      id: "blr-psa-003",
      title: "New lead added",
      description: "PES University entered pipeline as Stall Partner",
      timestamp: "2026-07-03T10:05:00+05:30",
      universityName: "PES University",
      tier: "Stall Partner",
      stage: "New",
      value: 95000,
    },
    {
      id: "blr-psa-004",
      title: "Negotiation started",
      description: "RV University reviewing Co-Presenting terms",
      timestamp: "2026-07-09T14:20:00+05:30",
      universityName: "RV University",
      tier: "Co-Presenting Partner",
      stage: "Negotiation",
      value: 750000,
    },
    {
      id: "blr-psa-005",
      title: "Meeting scheduled",
      description: "MS Ramaiah University stall discussion set for Jul 14",
      timestamp: "2026-07-08T11:00:00+05:30",
      universityName: "MS Ramaiah University of Applied Sciences",
      tier: "University Partner",
      stage: "Meeting Scheduled",
      value: 380000,
    },
    {
      id: "blr-psa-006",
      title: "Deal won — Presenting Partner",
      description: "Alliance University confirmed Presenting Partner for Bangalore",
      timestamp: "2026-07-05T17:45:00+05:30",
      universityName: "Alliance University",
      tier: "Presenting Partner",
      stage: "Won",
      value: 1100000,
    },
  ],
  leaderboard: [
    { name: "Arjun Mehta", deals: 12, won: 6, value: 2100000 },
    { name: "Priya Nair", deals: 10, won: 5, value: 1850000 },
    { name: "Ananya Shah", deals: 9, won: 4, value: 980000 },
    { name: "Sneha Iyer", deals: 7, won: 2, value: 620000 },
    { name: "Rohan Kapoor", deals: 6, won: 1, value: 400000 },
  ],
  deals: [
    {
      id: "blr-deal-001",
      universityName: "Christ University",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      status: "In Process",
      value: 550000,
      city: "Bangalore",
      owner: "Arjun Mehta",
      lastActivity: "2026-07-10T16:15:00+05:30",
      notes: "Awaiting academic council review",
    },
    {
      id: "blr-deal-002",
      universityName: "Jain University",
      tier: "Stall Partner",
      stage: "Won",
      status: "Confirmed",
      value: 100000,
      city: "Bangalore",
      owner: "Ananya Shah",
      lastActivity: "2026-07-06T09:30:00+05:30",
    },
    {
      id: "blr-deal-003",
      universityName: "PES University",
      tier: "Stall Partner",
      stage: "New",
      status: "In Process",
      value: 95000,
      city: "Bangalore",
      owner: "Ananya Shah",
      lastActivity: "2026-07-03T10:05:00+05:30",
    },
    {
      id: "blr-deal-004",
      universityName: "RV University",
      tier: "Co-Presenting Partner",
      stage: "Negotiation",
      status: "In Process",
      value: 750000,
      city: "Bangalore",
      owner: "Priya Nair",
      lastActivity: "2026-07-09T14:20:00+05:30",
    },
    {
      id: "blr-deal-005",
      universityName: "MS Ramaiah University of Applied Sciences",
      tier: "University Partner",
      stage: "Meeting Scheduled",
      status: "In Process",
      value: 380000,
      city: "Bangalore",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-08T11:00:00+05:30",
    },
    {
      id: "blr-deal-006",
      universityName: "Alliance University",
      tier: "Presenting Partner",
      stage: "Won",
      status: "Confirmed",
      value: 1100000,
      city: "Bangalore",
      owner: "Priya Nair",
      lastActivity: "2026-07-05T17:45:00+05:30",
    },
    {
      id: "blr-deal-007",
      universityName: "Reva University",
      tier: "Education Partner",
      stage: "Won",
      status: "Confirmed",
      value: 280000,
      city: "Bangalore",
      owner: "Arjun Mehta",
      lastActivity: "2026-07-04T12:30:00+05:30",
    },
    {
      id: "blr-deal-008",
      universityName: "Dayananda Sagar University",
      tier: "Knowledge Partner (Silver)",
      stage: "Contacted",
      status: "In Process",
      value: 300000,
      city: "Bangalore",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-07T15:10:00+05:30",
    },
    {
      id: "blr-deal-009",
      universityName: "CMR University",
      tier: "University Partner",
      stage: "Lost",
      status: "Lost",
      value: 350000,
      city: "Bangalore",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-02T11:00:00+05:30",
      notes: "Budget freeze for Q3",
    },
    {
      id: "blr-deal-010",
      universityName: "Presidency University",
      tier: "Education Partner",
      stage: "Won",
      status: "Confirmed",
      value: 220000,
      city: "Bangalore",
      owner: "Ananya Shah",
      lastActivity: "2026-07-01T16:00:00+05:30",
    },
    {
      id: "blr-deal-011",
      universityName: "Dayananda Sagar University",
      tier: "Co-Presenting Partner",
      stage: "Won",
      status: "Confirmed",
      value: 700000,
      city: "Bangalore",
      owner: "Priya Nair",
      lastActivity: "2026-07-04T12:20:00+05:30",
    },
    {
      id: "blr-deal-012",
      universityName: "Kristu Jayanti College",
      tier: "Knowledge Partner (Gold)",
      stage: "Won",
      status: "Confirmed",
      value: 500000,
      city: "Bangalore",
      owner: "Arjun Mehta",
      lastActivity: "2026-07-07T10:40:00+05:30",
    },
    {
      id: "blr-deal-013",
      universityName: "Garden City University",
      tier: "University Partner",
      stage: "Won",
      status: "Confirmed",
      value: 320000,
      city: "Bangalore",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-08T15:10:00+05:30",
    },
    {
      id: "blr-deal-014",
      universityName: "Atria University",
      tier: "Knowledge Partner (Silver)",
      stage: "Won",
      status: "Confirmed",
      value: 280000,
      city: "Bangalore",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-09T09:15:00+05:30",
    },
  ],
};

const bangaloreSlice: CityDashboardSlice = {
  kpis: [
    {
      id: "kpi-registrations",
      label: "Total Registrations",
      value: 22800,
      change: 21.2,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-events",
      label: "Active Events",
      value: 1,
      change: 0,
      changeType: "neutral",
      format: "number",
    },
    {
      id: "kpi-universities",
      label: "Approved Universities",
      value: 6,
      change: 1,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-revenue",
      label: "Registration Revenue",
      value: 5200000,
      change: 24.6,
      changeType: "increase",
      format: "currency",
    },
    {
      id: "kpi-checkins",
      label: "Check-ins Today",
      value: 3550,
      change: 48.1,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-conversion",
      label: "Registration Conversion",
      value: 76.2,
      change: 4.4,
      changeType: "increase",
      format: "percentage",
    },
  ],
  targets: [
    {
      id: "target-registrations",
      label: "Season Registrations",
      current: 22800,
      target: 28000,
      format: "number",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-revenue",
      label: "Registration Revenue",
      current: 5200000,
      target: 6200000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-sponsorship",
      label: "Partner Sponsorship",
      current: 4850000,
      target: 5200000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
  ],
  insights: [
    {
      id: "blr-insight-001",
      severity: "success",
      title: "Bangalore leads all three cities",
      description:
        "Bangalore holds 22,800 registrations — 52% of total volume and 57% above the three-city average. Keep school outreach concentrated in East and South Bangalore through July.",
    },
    {
      id: "blr-insight-002",
      severity: "info",
      title: "IB / IGCSE share is highest here",
      description:
        "International board registrations are 7.1% of Bangalore volume vs 6.2% overall. Partner with international schools for early-bird packs before August.",
    },
    {
      id: "blr-insight-003",
      severity: "warning",
      title: "Evening session under-indexed",
      description:
        "Evening registrations are 22.7% of Bangalore volume. Push after-school SMS campaigns in Whitefield and Electronic City catchments.",
    },
    {
      id: "blr-insight-004",
      severity: "success",
      title: "Partner sponsorship at 93% of city target",
      description:
        "₹48.5L secured against ₹52L Bangalore goal. Presenting and Co-Presenting tiers are on track; Stall Partner still needs 3 more closes.",
    },
  ],
  registrationTrend: [
    { name: "Jan", value: 620, registrations: 620 },
    { name: "Feb", value: 510, registrations: 510 },
    { name: "Mar", value: 760, registrations: 760 },
    { name: "Apr", value: 1100, registrations: 1100 },
    { name: "May", value: 1680, registrations: 1680 },
    { name: "Jun", value: 3040, registrations: 3040 },
    { name: "Jul", value: 4400, registrations: 4400 },
  ],
  eventPerformance: [
    {
      name: "Career Utsav Bangalore 2026",
      value: 22800,
      registrations: 22800,
      checkIns: 3550,
    },
  ],
  registrationsByStatus: [
    { name: "Confirmed", value: 9680 },
    { name: "Checked In", value: 11620 },
    { name: "Pending", value: 460 },
    { name: "Cancelled", value: 1040 },
  ],
  recentActivities: [
    {
      id: "blr-ra-001",
      type: "registration",
      title: "New registration",
      description: "Diya Krishnan registered for Bangalore 2026",
      timestamp: "2026-07-10T21:42:00+05:30",
      link: "/registrations/reg-blr-218",
    },
    {
      id: "blr-ra-002",
      type: "partner",
      title: "Negotiation",
      description: "Christ University Knowledge Partner (Gold) proposal sent",
      timestamp: "2026-07-10T16:15:00+05:30",
      link: "/partners/ptr-blr-002",
    },
    {
      id: "blr-ra-003",
      type: "event",
      title: "Capacity update",
      description: "Bangalore 2026 crossed 15,000 registrations",
      timestamp: "2026-07-08T10:00:00+05:30",
      link: "/events/evt-blr-001",
    },
    {
      id: "blr-ra-004",
      type: "university",
      title: "University approved",
      description: "Alliance University approved for Bangalore stall",
      timestamp: "2026-07-05T14:30:00+05:30",
      link: "/universities/uni-blr-006",
    },
    {
      id: "blr-ra-005",
      type: "partner",
      title: "Partner confirmed",
      description: "Bangalore Knowledge Partner package confirmed",
      timestamp: "2026-07-03T09:00:00+05:30",
      link: "/partners",
    },
    {
      id: "blr-ra-006",
      type: "system",
      title: "Capacity updated",
      description: "Bangalore early-bird registration target reviewed",
      timestamp: "2026-07-02T11:00:00+05:30",
      link: "/events",
    },
  ],
  upcomingTasks: [
    {
      id: "blr-task-001",
      title: "Review Bangalore early bird registration pace",
      priority: "High",
      dueDate: "2026-07-25T10:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-003",
      relatedResource: "registration",
    },
    {
      id: "blr-task-002",
      title: "Follow up Christ University Gold proposal",
      priority: "High",
      dueDate: "2026-07-14T17:00:00+05:30",
      status: "In Progress",
      assignedTo: "usr-002",
      relatedResource: "partner",
    },
    {
      id: "blr-task-003",
      title: "Confirm Palace Grounds AV walkthrough",
      priority: "Medium",
      dueDate: "2026-07-18T12:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-005",
      relatedResource: "event",
    },
    {
      id: "blr-task-004",
      title: "Confirm Bangalore venue floor plan",
      priority: "Low",
      dueDate: "2026-07-20T17:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-009",
      relatedResource: "event",
    },
  ],
  upcomingEvents: [
    {
      id: "evt-blr-001",
      title: "Career Utsav Bangalore 2026",
      startDate: "2026-08-15T09:00:00+05:30",
      city: "Bangalore",
      status: "Published",
      registrationCount: 22800,
      maxCapacity: 35000,
    },
  ],
  studentRegistration: bangaloreStudentRegistration,
  partnerSales: bangalorePartnerSales,
  vsAverage: buildVsAverage({
    registrations: 22800,
    revenue: 5200000,
    conversion: 76.2,
    pipeline: 13000000,
    checkIns: 3550,
  }),
};

// ─── Mysore (~27.5% volume) ─────────────────────────────────────────────────

const mysoreStudentRegistration: StudentRegistrationAnalytics = {
  total: 12000,
  target: 15500,
  todayCount: 112,
  weeklyGrowth: 13.2,
  dailyTrend: [
    { name: "Jun 26", value: 52 },
    { name: "Jun 27", value: 58 },
    { name: "Jun 28", value: 54 },
    { name: "Jun 29", value: 66 },
    { name: "Jun 30", value: 74 },
    { name: "Jul 1", value: 81 },
    { name: "Jul 2", value: 86 },
    { name: "Jul 3", value: 76 },
    { name: "Jul 4", value: 98 },
    { name: "Jul 5", value: 134 },
    { name: "Jul 6", value: 142 },
    { name: "Jul 7", value: 110 },
    { name: "Jul 8", value: 101 },
    { name: "Jul 9", value: 118 },
    { name: "Jul 10", value: 112 },
  ],
  byClass: [
    { name: "Class 4", value: 115, segment: "lower" },
    { name: "Class 5", value: 188, segment: "lower" },
    { name: "Class 6", value: 310, segment: "lower" },
    { name: "Class 7", value: 435, segment: "lower" },
    { name: "Class 8", value: 645, segment: "lower" },
    { name: "Class 9", value: 1680, segment: "core" },
    { name: "Class 10", value: 2460, segment: "core" },
    { name: "Class 11", value: 2820, segment: "core" },
    { name: "Class 12", value: 3347, segment: "core" },
  ],
  byStream: [
    { name: "Science", value: 5900 },
    { name: "Commerce", value: 3540 },
    { name: "Arts", value: 2560 },
  ],
  byBoard: [
    { name: "CBSE", value: 5120 },
    { name: "State Board", value: 3680 },
    { name: "ICSE", value: 1680 },
    { name: "PUC", value: 1120 },
    { name: "IB / IGCSE", value: 400 },
  ],
  byGender: [
    { name: "Female", value: 5930 },
    { name: "Male", value: 6070 },
  ],
  byCity: [{ name: "Mysore", value: 12000 }],
  byRegistrantCity: [
    { name: "Mysore", value: 6840 },
    { name: "Mandya", value: 1320 },
    { name: "Hassan", value: 980 },
    { name: "Nanjangud", value: 720 },
    { name: "Chamarajanagar", value: 640 },
    { name: "Hunsur", value: 520 },
    { name: "KR Nagar", value: 420 },
    { name: "Other / Out of state", value: 560 },
  ],
  bySeminar: buildSeminarInterest(12000),
  weeklyTrend: buildWeeklyTrend2026(12000, 1),
  bySession: [
    { name: "Morning", value: 5060 },
    { name: "Afternoon", value: 4200 },
    { name: "Evening", value: 2740 },
  ],
  bySource: [
    { name: "School Outreach", value: 4640 },
    { name: "Website", value: 3080 },
    { name: "Social Media", value: 1880 },
    { name: "Referral", value: 1420 },
    { name: "Partner", value: 980 },
  ],
  topSchools: [
    { name: "St. Joseph's Higher Secondary School", value: 412, city: "Mysore" },
    { name: "Marimallappa's High School", value: 368, city: "Mysore" },
    { name: "JSS Public School", value: 334, city: "Mysore" },
    { name: "Sadvidya High School", value: 298, city: "Mysore" },
    { name: "Mahajana Public School", value: 264, city: "Mysore" },
    { name: "Nirmala Convent School", value: 228, city: "Mysore" },
  ],
  topColleges: [
    { name: "University of Mysore", value: 286, city: "Mysore" },
    { name: "JSS Science and Technology University", value: 242, city: "Mysore" },
    { name: "Maharaja's College", value: 198, city: "Mysore" },
    { name: "Yuvaraja's College", value: 176, city: "Mysore" },
    { name: "St. Philomena's College", value: 154, city: "Mysore" },
    { name: "NIE Institute of Technology", value: 132, city: "Mysore" },
  ],
  liveFeed: [
    {
      id: "mys-live-001",
      studentName: "Sanjana Gowda",
      classLabel: "Class 12",
      stream: "Science",
      board: "PUC",
      school: "Sadvidya Composite PU College",
      city: "Mysore",
      timestamp: "2026-07-10T21:40:00+05:30",
    },
    {
      id: "mys-live-002",
      studentName: "Rohan Urs",
      classLabel: "Class 11",
      stream: "Commerce",
      board: "State Board",
      school: "Marimallappa's High School",
      city: "Mysore",
      timestamp: "2026-07-10T21:33:00+05:30",
    },
    {
      id: "mys-live-003",
      studentName: "Priya Nanjappa",
      classLabel: "Class 10",
      stream: "Science",
      board: "CBSE",
      school: "JSS Public School",
      city: "Mysore",
      timestamp: "2026-07-10T21:25:00+05:30",
    },
    {
      id: "mys-live-004",
      studentName: "Aditya Wodeyar",
      classLabel: "Class 9",
      stream: "Arts",
      board: "ICSE",
      school: "St. Joseph's Higher Secondary School",
      city: "Mysore",
      timestamp: "2026-07-10T21:18:00+05:30",
    },
    {
      id: "mys-live-005",
      studentName: "Kavya Shastry",
      classLabel: "Class 12",
      stream: "Science",
      board: "CBSE",
      school: "Mahajana Public School",
      city: "Mysore",
      timestamp: "2026-07-10T21:11:00+05:30",
    },
    {
      id: "mys-live-006",
      studentName: "Nikhil Ramesh",
      classLabel: "Class 8",
      board: "State Board",
      school: "Nirmala Convent School",
      city: "Mysore",
      timestamp: "2026-07-10T21:04:00+05:30",
    },
  ],
};

const mysorePartnerSales: PartnerSalesAnalytics = {
  totalPartners: 25,
  confirmed: 10,
  inProcess: 12,
  lost: 3,
  pipelineValue: 7000000,
  wonValue: 2600000,
  conversionRate: 40.0,
  byTier: [
    { name: "Stall Partner", value: 5, amount: 500000 },
    { name: "Education Partner", value: 4, amount: 800000 },
    { name: "Knowledge Partner (Silver)", value: 4, amount: 1200000 },
    { name: "Knowledge Partner (Gold)", value: 3, amount: 1500000 },
    { name: "University Partner", value: 5, amount: 1500000 },
    { name: "Co-Presenting Partner", value: 3, amount: 1500000 },
    { name: "Presenting Partner", value: 1, amount: 1000000 },
  ],
  byStage: [
    { name: "New", count: 4, amount: 900000 },
    { name: "Contacted", count: 3, amount: 780000 },
    { name: "Meeting Scheduled", count: 3, amount: 880000 },
    { name: "Negotiation", count: 5, amount: 2220000 },
    { name: "Won", count: 7, amount: 2600000 },
    { name: "Lost", count: 3, amount: 820000 },
  ],
  byStatus: [
    { name: "Confirmed", value: 10 },
    { name: "In Process", value: 12 },
    { name: "Lost", value: 3 },
  ],
  byCity: [
    { name: "Mysore", value: 10 },
  ],
  tierProgress: [
    { name: "Stall Partner", current: 5, target: 8, value: 500000 },
    { name: "Education Partner", current: 4, target: 6, value: 800000 },
    { name: "Knowledge Partner (Silver)", current: 4, target: 5, value: 1200000 },
    { name: "Knowledge Partner (Gold)", current: 3, target: 4, value: 1500000 },
    { name: "University Partner", current: 5, target: 6, value: 1500000 },
    { name: "Co-Presenting Partner", current: 3, target: 4, value: 1500000 },
    { name: "Presenting Partner", current: 1, target: 2, value: 1000000 },
  ],
  recentActivity: [
    {
      id: "mys-psa-001",
      title: "Deal won — University Partner",
      description: "University of Mysore confirmed University Partner",
      timestamp: "2026-07-09T15:30:00+05:30",
      universityName: "University of Mysore",
      tier: "University Partner",
      stage: "Won",
      value: 420000,
    },
    {
      id: "mys-psa-002",
      title: "Negotiation",
      description: "JSS STU received Knowledge Partner (Gold) proposal",
      timestamp: "2026-07-08T12:00:00+05:30",
      universityName: "JSS Science and Technology University",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      value: 480000,
    },
    {
      id: "mys-psa-003",
      title: "Meeting scheduled",
      description: "NIE Mysore Education Partner discussion set for Jul 13",
      timestamp: "2026-07-07T10:45:00+05:30",
      universityName: "NIE Institute of Technology",
      tier: "Education Partner",
      stage: "Meeting Scheduled",
      value: 200000,
    },
    {
      id: "mys-psa-004",
      title: "Negotiation started",
      description: "Amrita Mysore reviewing Co-Presenting terms",
      timestamp: "2026-07-06T16:20:00+05:30",
      universityName: "Amrita Vishwa Vidyapeetham, Mysore",
      tier: "Co-Presenting Partner",
      stage: "Negotiation",
      value: 650000,
    },
    {
      id: "mys-psa-005",
      title: "New lead added",
      description: "Vidya Vikas Institute entered pipeline as Stall Partner",
      timestamp: "2026-07-05T09:15:00+05:30",
      universityName: "Vidya Vikas Institute of Engineering",
      tier: "Stall Partner",
      stage: "New",
      value: 90000,
    },
    {
      id: "mys-psa-006",
      title: "Deal lost",
      description: "ATME College declined Stall Partner for this season",
      timestamp: "2026-07-04T14:00:00+05:30",
      universityName: "ATME College of Engineering",
      tier: "Stall Partner",
      stage: "Lost",
      value: 85000,
    },
  ],
  leaderboard: [
    { name: "Sneha Iyer", deals: 8, won: 4, value: 980000 },
    { name: "Priya Nair", deals: 6, won: 3, value: 820000 },
    { name: "Rohan Kapoor", deals: 5, won: 2, value: 540000 },
    { name: "Arjun Mehta", deals: 4, won: 1, value: 260000 },
    { name: "Ananya Shah", deals: 2, won: 0, value: 0 },
  ],
  deals: [
    {
      id: "mys-deal-001",
      universityName: "University of Mysore",
      tier: "University Partner",
      stage: "Won",
      status: "Confirmed",
      value: 420000,
      city: "Mysore",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-09T15:30:00+05:30",
    },
    {
      id: "mys-deal-002",
      universityName: "JSS Science and Technology University",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      status: "In Process",
      value: 480000,
      city: "Mysore",
      owner: "Priya Nair",
      lastActivity: "2026-07-08T12:00:00+05:30",
      notes: "Awaiting syndicate approval",
    },
    {
      id: "mys-deal-003",
      universityName: "NIE Institute of Technology",
      tier: "Education Partner",
      stage: "Meeting Scheduled",
      status: "In Process",
      value: 200000,
      city: "Mysore",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-07T10:45:00+05:30",
    },
    {
      id: "mys-deal-004",
      universityName: "Amrita Vishwa Vidyapeetham, Mysore",
      tier: "Co-Presenting Partner",
      stage: "Negotiation",
      status: "In Process",
      value: 650000,
      city: "Mysore",
      owner: "Priya Nair",
      lastActivity: "2026-07-06T16:20:00+05:30",
    },
    {
      id: "mys-deal-005",
      universityName: "Vidya Vikas Institute of Engineering",
      tier: "Stall Partner",
      stage: "New",
      status: "In Process",
      value: 90000,
      city: "Mysore",
      owner: "Ananya Shah",
      lastActivity: "2026-07-05T09:15:00+05:30",
    },
    {
      id: "mys-deal-006",
      universityName: "ATME College of Engineering",
      tier: "Stall Partner",
      stage: "Lost",
      status: "Lost",
      value: 85000,
      city: "Mysore",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-04T14:00:00+05:30",
      notes: "Deferred to next season",
    },
    {
      id: "mys-deal-007",
      universityName: "Maharaja Institute of Technology",
      tier: "Knowledge Partner (Silver)",
      stage: "Won",
      status: "Confirmed",
      value: 280000,
      city: "Mysore",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-03T11:20:00+05:30",
    },
    {
      id: "mys-deal-008",
      universityName: "GSSS Institute of Engineering",
      tier: "Education Partner",
      stage: "Won",
      status: "Confirmed",
      value: 180000,
      city: "Mysore",
      owner: "Arjun Mehta",
      lastActivity: "2026-07-02T13:40:00+05:30",
    },
  ],
};

const mysoreSlice: CityDashboardSlice = {
  kpis: [
    {
      id: "kpi-registrations",
      label: "Total Registrations",
      value: 12000,
      change: 15.8,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-events",
      label: "Active Events",
      value: 1,
      change: 0,
      changeType: "neutral",
      format: "number",
    },
    {
      id: "kpi-universities",
      label: "Approved Universities",
      value: 4,
      change: 1,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-revenue",
      label: "Registration Revenue",
      value: 2700000,
      change: 18.4,
      changeType: "increase",
      format: "currency",
    },
    {
      id: "kpi-checkins",
      label: "Check-ins Today",
      value: 1850,
      change: 38.6,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-conversion",
      label: "Registration Conversion",
      value: 71.4,
      change: 2.9,
      changeType: "increase",
      format: "percentage",
    },
  ],
  targets: [
    {
      id: "target-registrations",
      label: "Season Registrations",
      current: 12000,
      target: 15500,
      format: "number",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-revenue",
      label: "Registration Revenue",
      current: 2700000,
      target: 3400000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-sponsorship",
      label: "Partner Sponsorship",
      current: 2600000,
      target: 3000000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
  ],
  insights: [
    {
      id: "mys-insight-001",
      severity: "info",
      title: "Mysore holds steady mid-market share",
      description:
        "Mysore contributes 12,000 registrations (27.5% of total). State Board share is higher than Bangalore — lean into PUC and State Board school clusters.",
    },
    {
      id: "mys-insight-002",
      severity: "warning",
      title: "Presenting Partner still open",
      description:
        "Only 1 of 2 Presenting Partner slots filled. Prioritise Amrita Mysore Co-Presenting close and open a second Presenting conversation this week.",
    },
    {
      id: "mys-insight-003",
      severity: "success",
      title: "School outreach outperforming website",
      description:
        "School Outreach drives 38.7% of Mysore registrations. Expand JSS and Marimallappa feeder programmes before August.",
    },
    {
      id: "mys-insight-004",
      severity: "critical",
      title: "Capacity pace needs a lift",
      description:
        "Mysore is at 77% of season target with 36 days to event. Weekend walk-in camps in VV Mohalla and Gokulam can close the gap.",
    },
  ],
  registrationTrend: [
    { name: "Jan", value: 330, registrations: 330 },
    { name: "Feb", value: 270, registrations: 270 },
    { name: "Mar", value: 400, registrations: 400 },
    { name: "Apr", value: 580, registrations: 580 },
    { name: "May", value: 880, registrations: 880 },
    { name: "Jun", value: 1600, registrations: 1600 },
    { name: "Jul", value: 2310, registrations: 2310 },
  ],
  eventPerformance: [
    {
      name: "Career Utsav Mysore 2026",
      value: 12000,
      registrations: 12000,
      checkIns: 1850,
    },
  ],
  registrationsByStatus: [
    { name: "Confirmed", value: 5100 },
    { name: "Checked In", value: 6120 },
    { name: "Pending", value: 245 },
    { name: "Cancelled", value: 535 },
  ],
  recentActivities: [
    {
      id: "mys-ra-001",
      type: "registration",
      title: "New registration",
      description: "Sanjana Gowda registered for Mysore 2026",
      timestamp: "2026-07-10T21:40:00+05:30",
      link: "/registrations/reg-mys-112",
    },
    {
      id: "mys-ra-002",
      type: "partner",
      title: "Deal won",
      description: "University of Mysore confirmed as University Partner",
      timestamp: "2026-07-09T15:30:00+05:30",
      link: "/partners/ptr-mys-001",
    },
    {
      id: "mys-ra-003",
      type: "university",
      title: "University pending",
      description: "JSS STU Gold proposal under review",
      timestamp: "2026-07-08T12:00:00+05:30",
      link: "/universities/uni-mys-002",
    },
    {
      id: "mys-ra-004",
      type: "event",
      title: "Venue confirmed",
      description: "Mysore Palace Grounds booking confirmed for Sep 12",
      timestamp: "2026-07-06T10:00:00+05:30",
      link: "/events/evt-mys-001",
    },
    {
      id: "mys-ra-005",
      type: "partner",
      title: "Partner contacted",
      description: "Mysore University Partner follow-up completed",
      timestamp: "2026-07-04T09:30:00+05:30",
      link: "/partners",
    },
  ],
  upcomingTasks: [
    {
      id: "mys-task-001",
      title: "Close Amrita Mysore Co-Presenting negotiation",
      priority: "High",
      dueDate: "2026-07-15T17:00:00+05:30",
      status: "In Progress",
      assignedTo: "usr-002",
      relatedResource: "partner",
    },
    {
      id: "mys-task-002",
      title: "Schedule weekend walk-in camp in Gokulam",
      priority: "High",
      dueDate: "2026-07-19T10:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-003",
      relatedResource: "event",
    },
    {
      id: "mys-task-003",
      title: "Follow up JSS STU Gold proposal",
      priority: "Medium",
      dueDate: "2026-07-16T17:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-002",
      relatedResource: "partner",
    },
    {
      id: "mys-task-004",
      title: "Finalize Mysore seminar seat allotments",
      priority: "Medium",
      dueDate: "2026-07-22T17:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-004",
      relatedResource: "partner",
    },
  ],
  upcomingEvents: [
    {
      id: "evt-mys-001",
      title: "Career Utsav Mysore 2026",
      startDate: "2026-09-12T09:00:00+05:30",
      city: "Mysore",
      status: "Published",
      registrationCount: 12000,
      maxCapacity: 18000,
    },
  ],
  studentRegistration: mysoreStudentRegistration,
  partnerSales: mysorePartnerSales,
  vsAverage: buildVsAverage({
    registrations: 12000,
    revenue: 2700000,
    conversion: 71.4,
    pipeline: 7000000,
    checkIns: 1850,
  }),
};

// ─── Hubli (~20.2% volume) ──────────────────────────────────────────────────

const hubliStudentRegistration: StudentRegistrationAnalytics = {
  total: 8820,
  target: 11500,
  todayCount: 82,
  weeklyGrowth: 11.4,
  dailyTrend: [
    { name: "Jun 26", value: 36 },
    { name: "Jun 27", value: 44 },
    { name: "Jun 28", value: 40 },
    { name: "Jun 29", value: 49 },
    { name: "Jun 30", value: 53 },
    { name: "Jul 1", value: 59 },
    { name: "Jul 2", value: 62 },
    { name: "Jul 3", value: 56 },
    { name: "Jul 4", value: 70 },
    { name: "Jul 5", value: 99 },
    { name: "Jul 6", value: 107 },
    { name: "Jul 7", value: 80 },
    { name: "Jul 8", value: 74 },
    { name: "Jul 9", value: 88 },
    { name: "Jul 10", value: 82 },
  ],
  byClass: [
    { name: "Class 4", value: 85, segment: "lower" },
    { name: "Class 5", value: 137, segment: "lower" },
    { name: "Class 6", value: 225, segment: "lower" },
    { name: "Class 7", value: 320, segment: "lower" },
    { name: "Class 8", value: 475, segment: "lower" },
    { name: "Class 9", value: 1240, segment: "core" },
    { name: "Class 10", value: 1800, segment: "core" },
    { name: "Class 11", value: 2080, segment: "core" },
    { name: "Class 12", value: 2458, segment: "core" },
  ],
  byStream: [
    { name: "Science", value: 4340 },
    { name: "Commerce", value: 2580 },
    { name: "Arts", value: 1900 },
  ],
  byBoard: [
    { name: "CBSE", value: 3780 },
    { name: "State Board", value: 2700 },
    { name: "ICSE", value: 1240 },
    { name: "PUC", value: 410 },
    { name: "IB / IGCSE", value: 690 },
  ],
  byGender: [
    { name: "Female", value: 4350 },
    { name: "Male", value: 4470 },
  ],
  byCity: [{ name: "Hubli", value: 8820 }],
  byRegistrantCity: [
    { name: "Hubli", value: 4120 },
    { name: "Dharwad", value: 1860 },
    { name: "Belagavi", value: 980 },
    { name: "Gadag", value: 640 },
    { name: "Haveri", value: 520 },
    { name: "Bagalkot", value: 380 },
    { name: "Koppal", value: 160 },
    { name: "Other / Out of state", value: 160 },
  ],
  bySeminar: buildSeminarInterest(8820),
  weeklyTrend: buildWeeklyTrend2026(8820, 0.94),
  bySession: [
    { name: "Morning", value: 3720 },
    { name: "Afternoon", value: 3100 },
    { name: "Evening", value: 2000 },
  ],
  bySource: [
    { name: "School Outreach", value: 3380 },
    { name: "Website", value: 2280 },
    { name: "Social Media", value: 1380 },
    { name: "Referral", value: 1020 },
    { name: "Partner", value: 760 },
  ],
  topSchools: [
    { name: "KLE Society's School", value: 298, city: "Hubli" },
    { name: "St. Mary's High School", value: 264, city: "Hubli" },
    { name: "Basel Mission English Medium School", value: 238, city: "Hubli" },
    { name: "Pavan English Medium School", value: 212, city: "Hubli" },
    { name: "Chetan Public School", value: 186, city: "Hubli" },
    { name: "Vidya Bharati School", value: 164, city: "Hubli" },
  ],
  topColleges: [
    { name: "KLE Technological University", value: 214, city: "Hubli" },
    { name: "BVB College of Engineering", value: 188, city: "Hubli" },
    { name: "Karnatak University Dharwad", value: 162, city: "Hubli" },
    { name: "SDM College of Engineering", value: 148, city: "Hubli" },
    { name: "JSS Banashankari Arts College", value: 126, city: "Hubli" },
    { name: "PC Jabin Science College", value: 108, city: "Hubli" },
  ],
  liveFeed: [
    {
      id: "hbl-live-001",
      studentName: "Aishwarya Patil",
      classLabel: "Class 12",
      stream: "Science",
      board: "State Board",
      school: "KLE Society's PU College",
      city: "Hubli",
      timestamp: "2026-07-10T21:39:00+05:30",
    },
    {
      id: "hbl-live-002",
      studentName: "Rahul Desai",
      classLabel: "Class 11",
      stream: "Commerce",
      board: "CBSE",
      school: "Chetan Public School",
      city: "Hubli",
      timestamp: "2026-07-10T21:32:00+05:30",
    },
    {
      id: "hbl-live-003",
      studentName: "Sneha Kulkarni",
      classLabel: "Class 10",
      stream: "Science",
      board: "ICSE",
      school: "St. Mary's High School",
      city: "Hubli",
      timestamp: "2026-07-10T21:24:00+05:30",
    },
    {
      id: "hbl-live-004",
      studentName: "Vikram Shettar",
      classLabel: "Class 9",
      stream: "Arts",
      board: "State Board",
      school: "Basel Mission English Medium School",
      city: "Hubli",
      timestamp: "2026-07-10T21:16:00+05:30",
    },
    {
      id: "hbl-live-005",
      studentName: "Pooja Hiremath",
      classLabel: "Class 12",
      stream: "Science",
      board: "CBSE",
      school: "Pavan English Medium School",
      city: "Hubli",
      timestamp: "2026-07-10T21:09:00+05:30",
    },
    {
      id: "hbl-live-006",
      studentName: "Karthik Bhat",
      classLabel: "Class 8",
      board: "CBSE",
      school: "Vidya Bharati School",
      city: "Hubli",
      timestamp: "2026-07-10T21:02:00+05:30",
    },
  ],
};

const hubliPartnerSales: PartnerSalesAnalytics = {
  totalPartners: 17,
  confirmed: 6,
  inProcess: 8,
  lost: 3,
  pipelineValue: 4850000,
  wonValue: 1800000,
  conversionRate: 35.3,
  byTier: [
    { name: "Stall Partner", value: 4, amount: 400000 },
    { name: "Education Partner", value: 3, amount: 600000 },
    { name: "Knowledge Partner (Silver)", value: 2, amount: 600000 },
    { name: "Knowledge Partner (Gold)", value: 1, amount: 500000 },
    { name: "University Partner", value: 3, amount: 900000 },
    { name: "Co-Presenting Partner", value: 2, amount: 1000000 },
    { name: "Presenting Partner", value: 2, amount: 2000000 },
  ],
  byStage: [
    { name: "New", count: 3, amount: 620000 },
    { name: "Contacted", count: 2, amount: 530000 },
    { name: "Meeting Scheduled", count: 1, amount: 600000 },
    { name: "Negotiation", count: 3, amount: 1500000 },
    { name: "Won", count: 5, amount: 1800000 },
    { name: "Lost", count: 3, amount: 550000 },
  ],
  byStatus: [
    { name: "Confirmed", value: 6 },
    { name: "In Process", value: 8 },
    { name: "Lost", value: 3 },
  ],
  byCity: [
    { name: "Hubli", value: 6 },
  ],
  tierProgress: [
    { name: "Stall Partner", current: 4, target: 5, value: 400000 },
    { name: "Education Partner", current: 3, target: 4, value: 600000 },
    { name: "Knowledge Partner (Silver)", current: 2, target: 2, value: 600000 },
    { name: "Knowledge Partner (Gold)", current: 1, target: 2, value: 500000 },
    { name: "University Partner", current: 3, target: 3, value: 900000 },
    { name: "Co-Presenting Partner", current: 2, target: 2, value: 1000000 },
    { name: "Presenting Partner", current: 2, target: 2, value: 2000000 },
  ],
  recentActivity: [
    {
      id: "hbl-psa-001",
      title: "Deal won — Presenting Partner",
      description: "KLE Technological University confirmed Presenting Partner",
      timestamp: "2026-07-09T16:00:00+05:30",
      universityName: "KLE Technological University",
      tier: "Presenting Partner",
      stage: "Won",
      value: 950000,
    },
    {
      id: "hbl-psa-002",
      title: "Negotiation",
      description: "SDM College received Knowledge Partner (Gold) proposal",
      timestamp: "2026-07-08T11:30:00+05:30",
      universityName: "SDM College of Engineering",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      value: 420000,
    },
    {
      id: "hbl-psa-003",
      title: "Meeting scheduled",
      description: "BVB College Co-Presenting discussion set for Jul 15",
      timestamp: "2026-07-07T14:10:00+05:30",
      universityName: "BVB College of Engineering",
      tier: "Co-Presenting Partner",
      stage: "Meeting Scheduled",
      value: 550000,
    },
    {
      id: "hbl-psa-004",
      title: "New lead added",
      description: "PC Jabin Science College entered as Stall Partner",
      timestamp: "2026-07-06T09:40:00+05:30",
      universityName: "PC Jabin Science College",
      tier: "Stall Partner",
      stage: "New",
      value: 80000,
    },
    {
      id: "hbl-psa-005",
      title: "Deal won — University Partner",
      description: "Karnatak University Dharwad confirmed University Partner",
      timestamp: "2026-07-04T15:20:00+05:30",
      universityName: "Karnatak University Dharwad",
      tier: "University Partner",
      stage: "Won",
      value: 320000,
    },
    {
      id: "hbl-psa-006",
      title: "Deal lost",
      description: "AGMR College declined Education Partner for this season",
      timestamp: "2026-07-03T12:00:00+05:30",
      universityName: "AGMR College of Engineering",
      tier: "Education Partner",
      stage: "Lost",
      value: 150000,
    },
  ],
  leaderboard: [
    { name: "Rohan Kapoor", deals: 6, won: 3, value: 720000 },
    { name: "Sneha Iyer", deals: 4, won: 2, value: 540000 },
    { name: "Ananya Shah", deals: 3, won: 1, value: 320000 },
    { name: "Arjun Mehta", deals: 2, won: 0, value: 0 },
    { name: "Priya Nair", deals: 2, won: 0, value: 220000 },
  ],
  deals: [
    {
      id: "hbl-deal-001",
      universityName: "KLE Technological University",
      tier: "Presenting Partner",
      stage: "Won",
      status: "Confirmed",
      value: 950000,
      city: "Hubli",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-09T16:00:00+05:30",
      notes: "Flagship North Karnataka presenting package",
    },
    {
      id: "hbl-deal-002",
      universityName: "SDM College of Engineering",
      tier: "Knowledge Partner (Gold)",
      stage: "Negotiation",
      status: "In Process",
      value: 420000,
      city: "Hubli",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-08T11:30:00+05:30",
    },
    {
      id: "hbl-deal-003",
      universityName: "BVB College of Engineering",
      tier: "Co-Presenting Partner",
      stage: "Meeting Scheduled",
      status: "In Process",
      value: 550000,
      city: "Hubli",
      owner: "Priya Nair",
      lastActivity: "2026-07-07T14:10:00+05:30",
    },
    {
      id: "hbl-deal-004",
      universityName: "PC Jabin Science College",
      tier: "Stall Partner",
      stage: "New",
      status: "In Process",
      value: 80000,
      city: "Hubli",
      owner: "Ananya Shah",
      lastActivity: "2026-07-06T09:40:00+05:30",
    },
    {
      id: "hbl-deal-005",
      universityName: "Karnatak University Dharwad",
      tier: "University Partner",
      stage: "Won",
      status: "Confirmed",
      value: 320000,
      city: "Hubli",
      owner: "Rohan Kapoor",
      lastActivity: "2026-07-04T15:20:00+05:30",
    },
    {
      id: "hbl-deal-006",
      universityName: "AGMR College of Engineering",
      tier: "Education Partner",
      stage: "Lost",
      status: "Lost",
      value: 150000,
      city: "Hubli",
      owner: "Arjun Mehta",
      lastActivity: "2026-07-03T12:00:00+05:30",
      notes: "Budget freeze for Q3",
    },
    {
      id: "hbl-deal-007",
      universityName: "KLE Institute of Technology",
      tier: "Education Partner",
      stage: "Won",
      status: "Confirmed",
      value: 190000,
      city: "Hubli",
      owner: "Sneha Iyer",
      lastActivity: "2026-07-02T10:15:00+05:30",
    },
    {
      id: "hbl-deal-008",
      universityName: "Tontadarya College of Engineering",
      tier: "Stall Partner",
      stage: "Contacted",
      status: "In Process",
      value: 75000,
      city: "Hubli",
      owner: "Ananya Shah",
      lastActivity: "2026-07-01T14:50:00+05:30",
    },
  ],
};

const hubliSlice: CityDashboardSlice = {
  kpis: [
    {
      id: "kpi-registrations",
      label: "Total Registrations",
      value: 8820,
      change: 12.6,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-events",
      label: "Active Events",
      value: 1,
      change: 0,
      changeType: "neutral",
      format: "number",
    },
    {
      id: "kpi-universities",
      label: "Approved Universities",
      value: 2,
      change: 0,
      changeType: "neutral",
      format: "number",
    },
    {
      id: "kpi-revenue",
      label: "Registration Revenue",
      value: 1945000,
      change: 14.2,
      changeType: "increase",
      format: "currency",
    },
    {
      id: "kpi-checkins",
      label: "Check-ins Today",
      value: 1380,
      change: 32.4,
      changeType: "increase",
      format: "number",
    },
    {
      id: "kpi-conversion",
      label: "Registration Conversion",
      value: 66.8,
      change: 1.8,
      changeType: "increase",
      format: "percentage",
    },
  ],
  targets: [
    {
      id: "target-registrations",
      label: "Season Registrations",
      current: 8820,
      target: 11500,
      format: "number",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-revenue",
      label: "Registration Revenue",
      current: 1945000,
      target: 2400000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
    {
      id: "target-sponsorship",
      label: "Partner Sponsorship",
      current: 1800000,
      target: 1800000,
      format: "currency",
      periodLabel: "FY 2026 target",
    },
  ],
  insights: [
    {
      id: "hbl-insight-001",
      severity: "warning",
      title: "Hubli trails three-city average",
      description:
        "Hubli holds 8,820 registrations — 20% of total and 39% below the three-city average. Accelerate school outreach in Hubli-Dharwad twin-city catchments.",
    },
    {
      id: "hbl-insight-002",
      severity: "success",
      title: "Presenting Partner secured early",
      description:
        "KLE Technological University locked Presenting Partner at ₹9.5L. Use this as a reference close for remaining Gold and Co-Presenting deals.",
    },
    {
      id: "hbl-insight-003",
      severity: "critical",
      title: "Conversion lagging other cities",
      description:
        "Hubli conversion is 66.8% vs 72.5% overall. Review website funnel drop-offs and add WhatsApp follow-ups for Pending registrations.",
    },
    {
      id: "hbl-insight-004",
      severity: "info",
      title: "Partner sponsorship at city target",
      description:
        "₹18L won value matches Hubli sponsorship target. Focus remaining pipeline on Stall and Education Partner fills.",
    },
  ],
  registrationTrend: [
    { name: "Jan", value: 250, registrations: 250 },
    { name: "Feb", value: 200, registrations: 200 },
    { name: "Mar", value: 290, registrations: 290 },
    { name: "Apr", value: 420, registrations: 420 },
    { name: "May", value: 640, registrations: 640 },
    { name: "Jun", value: 1160, registrations: 1160 },
    { name: "Jul", value: 1690, registrations: 1690 },
  ],
  eventPerformance: [
    {
      name: "Career Utsav Hubli 2026",
      value: 8820,
      registrations: 8820,
      checkIns: 1380,
    },
  ],
  registrationsByStatus: [
    { name: "Confirmed", value: 3720 },
    { name: "Checked In", value: 4500 },
    { name: "Pending", value: 185 },
    { name: "Cancelled", value: 415 },
  ],
  recentActivities: [
    {
      id: "hbl-ra-001",
      type: "registration",
      title: "New registration",
      description: "Aishwarya Patil registered for Hubli 2026",
      timestamp: "2026-07-10T21:39:00+05:30",
      link: "/registrations/reg-hbl-082",
    },
    {
      id: "hbl-ra-002",
      type: "partner",
      title: "Deal won",
      description: "KLE Technological University confirmed Presenting Partner",
      timestamp: "2026-07-09T16:00:00+05:30",
      link: "/partners/ptr-hbl-001",
    },
    {
      id: "hbl-ra-003",
      type: "event",
      title: "Venue walkthrough",
      description: "Hubli Indoor Stadium AV walkthrough completed",
      timestamp: "2026-07-07T11:00:00+05:30",
      link: "/events/evt-hbl-001",
    },
    {
      id: "hbl-ra-004",
      type: "university",
      title: "University approved",
      description: "Karnatak University Dharwad approved for Hubli stall",
      timestamp: "2026-07-04T15:20:00+05:30",
      link: "/universities/uni-hbl-002",
    },
    {
      id: "hbl-ra-005",
      type: "system",
      title: "WhatsApp follow-up enabled",
      description: "Pending registration WhatsApp nudges enabled for Hubli",
      timestamp: "2026-07-03T10:00:00+05:30",
      link: "/settings",
    },
  ],
  upcomingTasks: [
    {
      id: "hbl-task-001",
      title: "Follow up SDM College Gold proposal",
      priority: "High",
      dueDate: "2026-07-14T17:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-002",
      relatedResource: "partner",
    },
    {
      id: "hbl-task-002",
      title: "Run Hubli-Dharwad school outreach blitz",
      priority: "High",
      dueDate: "2026-07-18T17:00:00+05:30",
      status: "In Progress",
      assignedTo: "usr-003",
      relatedResource: "registration",
    },
    {
      id: "hbl-task-003",
      title: "Confirm BVB Co-Presenting meeting",
      priority: "Medium",
      dueDate: "2026-07-15T12:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-002",
      relatedResource: "partner",
    },
    {
      id: "hbl-task-004",
      title: "Generate Hubli mid-season registration report",
      priority: "Medium",
      dueDate: "2026-07-20T17:00:00+05:30",
      status: "Pending",
      assignedTo: "usr-008",
      relatedResource: "report",
    },
  ],
  upcomingEvents: [
    {
      id: "evt-hbl-001",
      title: "Career Utsav Hubli 2026",
      startDate: "2026-10-10T09:00:00+05:30",
      city: "Hubli",
      status: "Published",
      registrationCount: 8820,
      maxCapacity: 14000,
    },
  ],
  studentRegistration: hubliStudentRegistration,
  partnerSales: hubliPartnerSales,
  vsAverage: buildVsAverage({
    registrations: 8820,
    revenue: 1945000,
    conversion: 66.8,
    pipeline: 4850000,
    checkIns: 1380,
  }),
};

// ─── Exports ────────────────────────────────────────────────────────────────

export const mockCitySlices: Record<OperatingCity, CityDashboardSlice> = {
  Bangalore: bangaloreSlice,
  Mysore: mysoreSlice,
  Hubli: hubliSlice,
};

export function buildAllCitiesRegistrationsByCity(): ChartDataPoint[] {
  return OPERATING_CITIES.map((city) => ({
    name: city,
    value: mockCitySlices[city].studentRegistration.total,
  }));
}
