import type { Event } from "@/types";

export const mockEvents: Event[] = [
  {
    id: "evt-001",
    title: "Career Uttsav Bengaluru 2026",
    slug: "career-uttsav-bengaluru-2026",
    description:
      "India's largest career fair in Bengaluru featuring 150+ universities, industry leaders, and career counselling sessions. Connect with top institutions from Karnataka and across India.",
    shortDescription: "150+ universities, career counselling & industry sessions in Bengaluru.",
    status: "Published",
    venue: "Palace Grounds",
    address: "Bellary Road, Vasanth Nagar",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560052",
    startDate: "2026-08-15",
    endDate: "2026-08-16",
    startTime: "09:00",
    endTime: "18:00",
    hallCount: 3,
    seminars: [
      {
        id: "sem-001-a",
        title: "How to select a stream – Art – Science – Commerce?",
        date: "2026-08-15",
        startTime: "10:00",
        endTime: "11:00",
        panelistSlots: 3,
        hall: 1,
      },
      {
        id: "sem-001-b",
        title: "Real Careers with Artificial Intelligence",
        date: "2026-08-15",
        startTime: "11:30",
        endTime: "12:30",
        panelistSlots: 2,
        hall: 2,
      },
      {
        id: "sem-001-c",
        title: "All about Overseas Education",
        date: "2026-08-16",
        startTime: "10:00",
        endTime: "11:00",
        panelistSlots: 4,
        hall: 1,
      },
      {
        id: "sem-001-d",
        title: "Medicine in the 21st century",
        date: "2026-08-16",
        startTime: "14:00",
        endTime: "15:00",
        panelistSlots: 3,
        hall: 3,
      },
    ],
    registrationDeadline: "2026-08-10T23:59:59+05:30",
    maxCapacity: 15000,
    registrationCount: 8420,
    checkInCount: 0,
    bannerImage: "/images/events/bengaluru-2026.jpg",
    isFeatured: true,
    tags: ["Engineering", "MBA", "Study Abroad", "Career Counselling"],
    createdBy: "usr-001",
    createdAt: "2025-11-01T10:00:00+05:30",
    updatedAt: "2026-06-20T14:30:00+05:30",
  },
];
