import type { GalleryImage } from "@/types";

export const mockGalleryImages: GalleryImage[] = [
  {
    id: "gal-001",
    title: "Delhi NCR 2026 Opening Ceremony",
    description: "Chief guest inaugurating Career Utsav Delhi NCR 2026 at Pragati Maidan.",
    imageUrl: "/images/gallery/delhi-opening-2026.jpg",
    thumbnailUrl: "/images/gallery/thumbs/delhi-opening-2026.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Event Highlights",
    uploadedBy: "usr-004",
    uploadedAt: "2026-07-05T10:30:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-002",
    title: "IIT Bombay Stall Interaction",
    description: "Students interacting with IIT Bombay admissions team at Delhi edition.",
    imageUrl: "/images/gallery/iit-bombay-stall.jpg",
    thumbnailUrl: "/images/gallery/thumbs/iit-bombay-stall.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Stalls",
    uploadedBy: "usr-009",
    uploadedAt: "2026-07-05T14:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-003",
    title: "Keynote by TCS Campus Head",
    description: "Mr. Amit Khanna delivering the opening keynote on future of IT careers.",
    imageUrl: "/images/gallery/tcs-keynote.jpg",
    thumbnailUrl: "/images/gallery/thumbs/tcs-keynote.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Speakers",
    uploadedBy: "usr-004",
    uploadedAt: "2026-07-05T11:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-004",
    title: "Student Registration Queue",
    description: "Early morning registration rush at Pragati Maidan entrance.",
    imageUrl: "/images/gallery/delhi-registration-queue.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Students",
    uploadedBy: "usr-005",
    uploadedAt: "2026-07-05T09:15:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-005",
    title: "Study Abroad Pavilion",
    description: "IDP Education counselling booth with students exploring UK and Canada options.",
    imageUrl: "/images/gallery/study-abroad-pavilion.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Stalls",
    uploadedBy: "usr-009",
    uploadedAt: "2026-07-06T15:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-006",
    title: "Mumbai 2025 Hackathon Finals",
    description: "Accenture-sponsored hackathon final round at NESCO Grounds.",
    imageUrl: "/images/gallery/mumbai-hackathon.jpg",
    eventId: "evt-003",
    eventName: "Career Utsav Mumbai 2025",
    category: "Workshops",
    uploadedBy: "usr-004",
    uploadedAt: "2025-12-10T17:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-007",
    title: "Symbiosis MBA Preview Session",
    description: "Dr. Anjali Kulkarni presenting MBA program highlights to prospective students.",
    imageUrl: "/images/gallery/symbiosis-session.jpg",
    eventId: "evt-003",
    eventName: "Career Utsav Mumbai 2025",
    category: "Speakers",
    uploadedBy: "usr-009",
    uploadedAt: "2025-12-10T14:30:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-008",
    title: "Excellence Award Ceremony",
    description: "Award presentation to top-performing university stalls at Mumbai 2025.",
    imageUrl: "/images/gallery/mumbai-awards.jpg",
    eventId: "evt-003",
    eventName: "Career Utsav Mumbai 2025",
    category: "Awards",
    uploadedBy: "usr-002",
    uploadedAt: "2025-12-11T18:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-009",
    title: "Bengaluru 2026 Banner Launch",
    description: "Marketing team unveiling the Bengaluru 2026 event banner at Palace Grounds.",
    imageUrl: "/images/gallery/bengaluru-banner-launch.jpg",
    eventId: "evt-001",
    eventName: "Career Utsav Bengaluru 2026",
    category: "Event Highlights",
    uploadedBy: "usr-003",
    uploadedAt: "2026-06-20T11:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-010",
    title: "Manipal University Stall Design",
    description: "Preview of MAHE Manipal's premium stall setup for Bengaluru edition.",
    imageUrl: "/images/gallery/manipal-stall-design.jpg",
    eventId: "evt-001",
    eventName: "Career Utsav Bengaluru 2026",
    category: "Stalls",
    uploadedBy: "usr-005",
    uploadedAt: "2026-06-25T10:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-011",
    title: "JEE Preparation Workshop",
    description: "BYJU'S conducting a live JEE problem-solving session for Class 12 students.",
    imageUrl: "/images/gallery/jee-workshop.jpg",
    eventId: "evt-001",
    eventName: "Career Utsav Bengaluru 2026",
    category: "Workshops",
    uploadedBy: "usr-009",
    uploadedAt: "2026-06-28T14:00:00+05:30",
    isPublished: false,
  },
  {
    id: "gal-012",
    title: "Pune 2025 Crowd Overview",
    description: "Aerial view of the bustling Auto Cluster Exhibition Center during peak hours.",
    imageUrl: "/images/gallery/pune-crowd.jpg",
    eventId: "evt-005",
    eventName: "Career Utsav Pune 2025",
    category: "Event Highlights",
    uploadedBy: "usr-004",
    uploadedAt: "2025-09-05T12:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-013",
    title: "Fergusson College Student Group",
    description: "Group of students from Fergusson College exploring university stalls in Pune.",
    imageUrl: "/images/gallery/pune-students.jpg",
    eventId: "evt-005",
    eventName: "Career Utsav Pune 2025",
    category: "Students",
    uploadedBy: "usr-005",
    uploadedAt: "2025-09-05T15:30:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-014",
    title: "Hyderabad Venue Setup",
    description: "HITEX Exhibition Centre being prepared for Career Utsav Hyderabad 2026.",
    imageUrl: "/images/gallery/hyderabad-setup.jpg",
    eventId: "evt-004",
    eventName: "Career Utsav Hyderabad 2026",
    category: "Event Highlights",
    uploadedBy: "usr-003",
    uploadedAt: "2026-06-15T09:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-015",
    title: "IIIT Hyderabad Faculty Panel",
    description: "Panel discussion on AI and machine learning careers at Hyderabad preview event.",
    imageUrl: "/images/gallery/iiit-panel.jpg",
    eventId: "evt-004",
    eventName: "Career Utsav Hyderabad 2026",
    category: "Speakers",
    uploadedBy: "usr-004",
    uploadedAt: "2026-06-18T16:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-016",
    title: "Volunteer Team Briefing",
    description: "Operations team briefing 50 volunteers before Delhi NCR event day.",
    imageUrl: "/images/gallery/volunteer-briefing.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Event Highlights",
    uploadedBy: "usr-005",
    uploadedAt: "2026-07-04T18:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-017",
    title: "Best Stall Award — DTU",
    description: "Delhi Technological University receiving the Best Government Stall award.",
    imageUrl: "/images/gallery/dtu-award.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Awards",
    uploadedBy: "usr-002",
    uploadedAt: "2026-07-06T17:30:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-018",
    title: "Career Counselling Corner",
    description: "One-on-one career counselling sessions for confused Class 12 students.",
    imageUrl: "/images/gallery/counselling-corner.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Students",
    uploadedBy: "usr-009",
    uploadedAt: "2026-07-06T13:00:00+05:30",
    isPublished: true,
  },
  {
    id: "gal-019",
    title: "Wipro Career Talk",
    description: "Wipro campus recruitment head sharing industry insights with engineering students.",
    imageUrl: "/images/gallery/wipro-career-talk.jpg",
    eventId: "evt-001",
    eventName: "Career Utsav Bengaluru 2026",
    category: "Speakers",
    uploadedBy: "usr-003",
    uploadedAt: "2026-06-30T11:00:00+05:30",
    isPublished: false,
  },
  {
    id: "gal-020",
    title: "Behind the Scenes — Media Coverage",
    description: "Times of India team filming event coverage at Delhi NCR edition.",
    imageUrl: "/images/gallery/media-coverage.jpg",
    eventId: "evt-002",
    eventName: "Career Utsav Delhi NCR 2026",
    category: "Event Highlights",
    uploadedBy: "usr-003",
    uploadedAt: "2026-07-05T16:00:00+05:30",
    isPublished: true,
  },
];
