import type { Partner } from "@/types";

export const mockPartners: Partner[] = [
  {
    id: "ptr-001",
    name: "Tata Consultancy Services",
    category: "Platinum Sponsor",
    logo: "/logos/tcs.png",
    website: "https://www.tcs.com",
    description: "India's largest IT services company and title sponsor of Career Utsav 2026.",
    contactPerson: "Mr. Amit Khanna",
    contactEmail: "campus.recruitment@tcs.com",
    contactPhone: "+91 22 6778 9595",
    city: "Mumbai",
    state: "Maharashtra",
    sponsorshipAmount: 2500000,
    benefits: ["Title branding", "Keynote slot", "Premium stall", "Digital campaign"],
    eventIds: ["evt-001", "evt-002", "evt-003"],
    isActive: true,
    createdAt: "2025-06-01T10:00:00+05:30",
    updatedAt: "2026-06-01T11:00:00+05:30",
  },
  {
    id: "ptr-002",
    name: "Infosys Limited",
    category: "Gold Sponsor",
    logo: "/logos/infosys.png",
    website: "https://www.infosys.com",
    description: "Global leader in next-generation digital services and consulting.",
    contactPerson: "Ms. Shruti Menon",
    contactEmail: "campus@infosys.com",
    contactPhone: "+91 80 2852 0261",
    city: "Bengaluru",
    state: "Karnataka",
    sponsorshipAmount: 1500000,
    benefits: ["Gold branding", "Workshop slot", "Recruitment booth"],
    eventIds: ["evt-001", "evt-004"],
    isActive: true,
    createdAt: "2025-07-15T09:00:00+05:30",
    updatedAt: "2026-05-20T10:00:00+05:30",
  },
  {
    id: "ptr-003",
    name: "HDFC Bank",
    category: "Gold Sponsor",
    logo: "/logos/hdfc-bank.png",
    website: "https://www.hdfcbank.com",
    description: "India's leading private sector bank supporting education finance initiatives.",
    contactPerson: "Mr. Rajiv Malhotra",
    contactEmail: "education.loans@hdfcbank.com",
    contactPhone: "+91 22 6160 6161",
    city: "Mumbai",
    state: "Maharashtra",
    sponsorshipAmount: 1200000,
    benefits: ["Education loan kiosk", "Financial literacy sessions"],
    eventIds: ["evt-002", "evt-003"],
    isActive: true,
    createdAt: "2025-08-01T11:00:00+05:30",
    updatedAt: "2026-04-10T14:00:00+05:30",
  },
  {
    id: "ptr-004",
    name: "The Times of India",
    category: "Media Partner",
    logo: "/logos/toi.png",
    website: "https://timesofindia.indiatimes.com",
    description: "Official media partner providing pre and post event coverage across India.",
    contactPerson: "Ms. Nisha Kapoor",
    contactEmail: "events@timesgroup.com",
    contactPhone: "+91 11 2337 1234",
    city: "New Delhi",
    state: "Delhi",
    benefits: ["Print coverage", "Digital promotion", "Social media amplification"],
    eventIds: ["evt-001", "evt-002", "evt-003", "evt-004"],
    isActive: true,
    createdAt: "2025-05-20T10:00:00+05:30",
    updatedAt: "2026-06-15T09:00:00+05:30",
  },
  {
    id: "ptr-005",
    name: "Razorpay",
    category: "Technology Partner",
    logo: "/logos/razorpay.png",
    website: "https://razorpay.com",
    description: "Payment gateway partner powering registration and ticket payments.",
    contactPerson: "Mr. Karan Bhatia",
    contactEmail: "partnerships@razorpay.com",
    contactPhone: "+91 80 6815 8700",
    city: "Bengaluru",
    state: "Karnataka",
    benefits: ["Payment integration", "Zero transaction fee for first 10K registrations"],
    eventIds: ["evt-001", "evt-002", "evt-004"],
    isActive: true,
    createdAt: "2025-09-01T09:00:00+05:30",
    updatedAt: "2026-06-01T10:00:00+05:30",
  },
  {
    id: "ptr-006",
    name: "IDP Education India",
    category: "Education Partner",
    logo: "/logos/idp.png",
    website: "https://www.idp.com/india",
    description: "Leading study abroad consultant partnering for international education sessions.",
    contactPerson: "Ms. Rebecca D'Souza",
    contactEmail: "india.partnerships@idp.com",
    contactPhone: "+91 11 4246 8888",
    city: "New Delhi",
    state: "Delhi",
    sponsorshipAmount: 800000,
    benefits: ["Study abroad pavilion", "Counselling sessions", "IELTS workshops"],
    eventIds: ["evt-002", "evt-004"],
    isActive: true,
    createdAt: "2025-10-10T10:00:00+05:30",
    updatedAt: "2026-05-25T11:00:00+05:30",
  },
  {
    id: "ptr-007",
    name: "Wipro Limited",
    category: "Silver Sponsor",
    logo: "/logos/wipro.png",
    website: "https://www.wipro.com",
    description: "Global IT, consulting and business process services company.",
    contactPerson: "Mr. Sanjeev Rao",
    contactEmail: "campus.hiring@wipro.com",
    contactPhone: "+91 80 2844 0011",
    city: "Bengaluru",
    state: "Karnataka",
    sponsorshipAmount: 750000,
    benefits: ["Silver branding", "Career talk session"],
    eventIds: ["evt-001"],
    isActive: true,
    createdAt: "2025-11-01T09:00:00+05:30",
    updatedAt: "2026-06-10T14:00:00+05:30",
  },
  {
    id: "ptr-008",
    name: "BYJU'S",
    category: "Silver Sponsor",
    logo: "/logos/byjus.png",
    website: "https://byjus.com",
    description: "EdTech partner providing JEE and NEET preparation workshops at events.",
    contactPerson: "Mr. Aditya Malhotra",
    contactEmail: "partnerships@byjus.com",
    contactPhone: "+91 80 4710 8888",
    city: "Bengaluru",
    state: "Karnataka",
    sponsorshipAmount: 600000,
    benefits: ["Exam prep workshops", "Scholarship announcements"],
    eventIds: ["evt-001", "evt-004"],
    isActive: true,
    createdAt: "2026-01-15T10:00:00+05:30",
    updatedAt: "2026-06-20T09:00:00+05:30",
  },
  {
    id: "ptr-009",
    name: "YourStory Media",
    category: "Media Partner",
    logo: "/logos/yourstory.png",
    website: "https://yourstory.com",
    description: "Digital media partner covering startup and career stories from events.",
    contactPerson: "Ms. Shradha Sharma",
    contactEmail: "partnerships@yourstory.com",
    contactPhone: "+91 80 4090 0000",
    city: "Bengaluru",
    state: "Karnataka",
    benefits: ["Startup spotlight segment", "Video coverage", "Newsletter feature"],
    eventIds: ["evt-001", "evt-003"],
    isActive: true,
    createdAt: "2025-08-20T11:00:00+05:30",
    updatedAt: "2026-03-01T10:00:00+05:30",
  },
  {
    id: "ptr-010",
    name: "Leverage Edu",
    category: "Education Partner",
    logo: "/logos/leverage-edu.png",
    website: "https://leverageedu.com",
    description: "Study abroad and career guidance platform for Indian students.",
    contactPerson: "Mr. Akshay Chaturvedi",
    contactEmail: "partners@leverageedu.com",
    contactPhone: "+91 11 4084 0000",
    city: "New Delhi",
    state: "Delhi",
    sponsorshipAmount: 500000,
    benefits: ["Counselling booths", "Webinar series", "Co-branded content"],
    eventIds: ["evt-002", "evt-006"],
    isActive: true,
    createdAt: "2026-02-01T09:00:00+05:30",
    updatedAt: "2026-06-18T15:00:00+05:30",
  },
  {
    id: "ptr-011",
    name: "Accenture India",
    category: "Gold Sponsor",
    logo: "/logos/accenture.png",
    website: "https://www.accenture.com/in-en",
    description: "Global professional services company with strong campus hiring program.",
    contactPerson: "Ms. Priyanka Das",
    contactEmail: "india.campus@accenture.com",
    contactPhone: "+91 22 6695 5000",
    city: "Mumbai",
    state: "Maharashtra",
    sponsorshipAmount: 1400000,
    benefits: ["Gold branding", "Hackathon sponsor", "Recruitment drive"],
    eventIds: ["evt-003"],
    isActive: false,
    createdAt: "2025-05-01T10:00:00+05:30",
    updatedAt: "2025-12-15T10:00:00+05:30",
  },
  {
    id: "ptr-012",
    name: "Zoho Corporation",
    category: "Technology Partner",
    logo: "/logos/zoho.png",
    website: "https://www.zoho.com",
    description: "SaaS company providing CRM and event management tools for Career Utsav.",
    contactPerson: "Mr. Sridhar Vembu",
    contactEmail: "partnerships@zohocorp.com",
    contactPhone: "+91 44 6965 6000",
    city: "Chennai",
    state: "Tamil Nadu",
    benefits: ["CRM integration", "Lead management dashboard"],
    eventIds: ["evt-006"],
    isActive: true,
    createdAt: "2026-05-01T10:00:00+05:30",
    updatedAt: "2026-06-25T11:00:00+05:30",
  },
];
